"""Wagwan Fam?

Revision ID: 8a954ace3a62
Revises: c95d5672b3dc
Create Date: 2023-09-22 19:30:30.684558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a954ace3a62'
down_revision = 'c95d5672b3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_messages_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_messages_username'), type_='unique')

    # ### end Alembic commands ###
